apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: kyverno-security-lab-tests
policies:
  - require-limits.yaml
  - restrict-privilege.yaml
  - restrict-root-user.yaml
  - mutate-security-context.yaml
resources:
  - bad-pod.yaml
  - bad-pod-priv.yaml
  - bad-pod-root.yaml
  - mutate-pod.yaml
  - good-pod.yaml
results:
  # 1. Require CPU & Memory Limits Policy
  - policy: require-cpu-memory-limits
    rule: check-cpu-memory-limits
    kind: Pod
    resources:
      - test-pod-bad
    result: fail
  - policy: require-cpu-memory-limits
    rule: check-cpu-memory-limits
    kind: Pod
    resources:
      - test-pod-good
    result: pass

  # 2. Restrict Privileged Containers Policy
  - policy: restrict-privileged-containers
    rule: validate-privileged
    kind: Pod
    resources:
      - test-pod-hacker-priv
    result: fail
  - policy: restrict-privileged-containers
    rule: validate-privileged
    kind: Pod
    resources:
      - test-pod-good
    result: pass

  # 3. Restrict Root User Policy
  - policy: restrict-root-user
    rule: validate-non-root
    kind: Pod
    resources:
      - test-pod-bad-root
    result: fail
  - policy: restrict-root-user
    rule: validate-non-root
    kind: Pod
    resources:
      - test-pod-good
    result: pass

  # 4. Mutate Pod Security Defaults Policy
  - policy: mutate-pod-security-defaults
    rule: inject-audit-label
    kind: Pod
    resources:
      - test-pod-mutate
    result: pass
    patchedResources: mutated-pod-expected.yaml
  - policy: mutate-pod-security-defaults
    rule: inject-allow-privilege-escalation
    kind: Pod
    resources:
      - test-pod-mutate
    result: pass
    patchedResources: mutated-pod-expected.yaml
